### ISSUE TITLE
Keep Popup on screen

### ISSUE THREAD

**Issue by sohayb** [martinjuhasz/MJPopupViewController#71]
Hello,
Is there a way to keep the Popup on screen if the user clicks outside the the Popup bounds, because the Popup gets dismissed.
Thanks

**Comment by kmuralidharan91** [comment]
Create an entire viewcontroller and set a view with your custom size and set the background as transperant. Now you cannot exit by touching outside of the view...
Hope it helps

**Comment by sohayb** [comment]
@kmuralidharan91 thanks  😀, but the thing is that I fixed it by adding a property o the category and set it from the ViewController, check my pull request.
